addSbtPlugin("com.github.cuzfrog" % "sbt-tmpfs" % "0.3.0")
//addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.8.2")
addSbtPlugin("com.dwijnand" % "sbt-dynver" % "2.0.0")
//addSbtPlugin("io.spray" % "sbt-revolver" % "0.8.0")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.5")
//addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-M15")